# Generated by Django 3.2.9 on 2021-11-03 08:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('parking', '0002_driverprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_price', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Minimun price to be charged')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('image', models.ImageField(upload_to='images/')),
                ('rate', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Rate per hour')),
                ('rows', models.IntegerField()),
                ('columns', models.IntegerField()),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='parkings', to='parking.location')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parking', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
