# Generated by Django 3.2.9 on 2021-11-03 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='profile_pic',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
